webtalk_init -webtalk_dir D:/Computer_Programming/Logic_Designer/LogicDesignLAB/lab1/Lab1_TeamX_comparator_4bit_testbenching/Lab1_TeamX_comparator_4bit_testbenching.sim/sim_1/behav/xsim/xsim.dir/comp_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Sep 24 16:27:30 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2960000" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bda2443a-6eee-4f3f-9d64-dc5556db4763" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "530c40175ad544f9b830171bd0319ee8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4800HS with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2895 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "272 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6760_KB" -context "xsim\\usage"
webtalk_transmit -clientid 113143044 -regid "" -xml D:/Computer_Programming/Logic_Designer/LogicDesignLAB/lab1/Lab1_TeamX_comparator_4bit_testbenching/Lab1_TeamX_comparator_4bit_testbenching.sim/sim_1/behav/xsim/xsim.dir/comp_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Computer_Programming/Logic_Designer/LogicDesignLAB/lab1/Lab1_TeamX_comparator_4bit_testbenching/Lab1_TeamX_comparator_4bit_testbenching.sim/sim_1/behav/xsim/xsim.dir/comp_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Computer_Programming/Logic_Designer/LogicDesignLAB/lab1/Lab1_TeamX_comparator_4bit_testbenching/Lab1_TeamX_comparator_4bit_testbenching.sim/sim_1/behav/xsim/xsim.dir/comp_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
